### PR TITLE
Create blog. First post: Defunctionalize the continuation

### PR DESCRIPTION
**Pull request by Lysxia**

### CODE REVIEW

**Comment by dunnl** [comment]
Awesome. I will merge this and #17 later today.

**Comment by dunnl** [comment]
At the moment there is no`blog.html` so the Blog link in the header doesn't point to anything. Did you mean to commit one? Also @euisuny we should probably ask the department if they have any guidance on how to manage the blog. I would love to get this up and running.

**Comment by Lysxia** [comment]
I indeed forgot blog.html.

It would be certainly good to know whether there are guidelines to 
follow. Should I bring up the topic on slack too?

**Comment by dunnl** [comment]
I emailed Benjamin to start a conversation about how to set things up in a way that makes sense. I'll post announcements on the Slack website channel, and I think at next PL club we'll get a discussion going before or after the main talk. Generally speaking the department supports the blog idea. I won't merge just yet but I'm sure we'll get this up soon.

**Comment by dunnl** [comment]
I merged this into a branch `blog-staging`. When we actually have everything ready to publish on Monday-ish then we can put everything into master and deploy. The code highlighting looks really good.

**Pull request merged**
