### PR TITLE
2020 May 15, First Three Posts

### PR DESCRIPTION
**Pull request by hgoldstein95**
This is WIP for now, do not merge.

### CODE REVIEW

**Comment by hgoldstein95** [comment]
Ready to review. @lag47 what do you think about `h2` vs `h3` for headings in the posts? Should we try to standardize or does it not matter? I tried changing all of Li-yao's to `h3`s but it messed up his table of contents...

**Comment by dunnl** [comment]
Semantically the headings should start at h2 since the title is h1. (I'm not sure if it's marked up that way at this time, but semantically.) The TOC cuts off a certain hard-coded depth that I can change or make per-post if that's valuable which might be the issue you had with Li-yao's post. Do you can to edit the rewriting post to h2?

**Comment by hgoldstein95** [comment]
Yeah, I'll do that. Maybe we can look into changing the CSS to make h2's a little smaller?

**Comment by dunnl** [comment]
On the welcome page, do you want to make those links to the two posts?

Other than that I'd say we can merge. I don't know if we can fix the headings easily today unless we scape together a hack. I think I looks good enough in the meantime but I agree, the whole typography could use some work. 

We can discuss on Slack the actual deploy and announcement.

**Comment by hgoldstein95** [comment]
I don't know how to do links between posts, but that seems like a good idea. Yeah, headings can be a later-on issue.

**Comment by dunnl** [comment]
I couldn't push my edits to the PR, so I added links and squashed the PR into `blog-staging` but Github evidently doesn't realize this merges the PR.

**Pull request closed without merging**
